http {
    server {
        listen :8082;
        root test/;
        location ~ \.py$ {
            cgi_pass /usr/bin/python3;
        }
    }

    server {
        listen :8084;
        root upload/;
        location /upload {
            upload_path upload/files/;
            root upload/files/;
            autoindex on;
        }
    }
}
