http {
    server {
        listen :8082;
        root quiz/;
        location ~ \.php$ {
            cgi_pass /usr/bin/php-cgi;
        }
    }

    server {
        listen :8088;
        root .;
        location ~ \.php$ {
            cgi_pass /usr/bin/php-cgi;
        }
    }

    server {
        listen :8084;
        root upload/;
        location /upload {
            upload_path upload/files/;
            root upload/files/;
            autoindex on;
        }
    }
}
